name: GitHub-Profile-Summary-Cards

on:
  # schedule:
  #   - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
      - uses: vn7n24fzkq/github-profile-summary-cards@4a9822e91a20eae650b9591769569976f0d578ba # release, 2026-07-24
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "master"
          THEME: "dracula"
          ANIMATION: "sequence"
          UTC_OFFSET: 1
          EXCLUDE: "Python,Java"
          AUTO_PUSH: true
